import { withPayload } from '@payloadcms/next/withPayload'

/** @type {import('next').NextConfig} */
const nextConfig = {
  async rewrites() {
    return [
      {
        // old URL generated by Payload
        source: '/api/media/file/:path*',
        // new location inside /public
        destination: '/media/:path*',
      },
    ]
  },

  images: {
    minimumCacheTTL: 12 * 60 * 60, // 12 hours

    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
      {
        protocol: 'http',
        hostname: '**',
      },
    ],
  },
}

export default withPayload(nextConfig, { devBundleServerPackages: false })
