import { withPayload } from '@payloadcms/next/withPayload'

/** @type {import('next').NextConfig} */
const nextConfig = {
  // async rewrites() {
  //   return [
  //     {
  //       // old URL generated by Payload
  //       source: '/api/media/file/:path*',
  //       // new location inside /public
  //       destination: '/media/:path*',
  //     },
  //   ]
  // },

  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: '**',
      },
      {
        protocol: 'http',
        hostname: '**',
      },
    ],
  },
}

export default withPayload(nextConfig, { devBundleServerPackages: false })

// import { withPayload } from '@payloadcms/next/withPayload'

// /** @type {import('next').NextConfig} */
// const nextConfig = {
//   images: {
//     remotePatterns: [
//       {
//         protocol: 'https',
//         hostname: 'res.cloudinary.com',
//         pathname: '/**',
//       },
//     ],
//     // minimumCacheTTL: 12 * 60 * 60, // keep if you still want it
//   },
//   // ⚠️ No rewrites needed—files come straight from Cloudinary
// }

// export default withPayload(nextConfig, { devBundleServerPackages: false })
